pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    bat 'g++ -o PES2UG22CS149 hello1.cpp'  // Compile C++ file (for Windows)
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    bat 'PES2UG22CS149'  // Run compiled program
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'  // Placeholder
            }
        }
    }

    post {
        failure {
            script {
                echo 'Pipeline failed'
            }
        }
    }
}
