pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'g++ -o PES2UG22CS149-1 hello1.cpp'  // Compile C++ file
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh './PES2UG22CS149-1'  // Run the compiled C++ program
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'  // Simulating deployment
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'  // Error handling
        }
    }
}
